-- 1. إدخال البيانات الأساسية مع تلافي التعارض
INSERT INTO public.brands (id, name, name_ar, notes) VALUES 
(1, 'FABER CASTLE', 'فابر كاستل', NULL),
(2, 'DELI', 'ديلي', NULL),
(3, 'MADEN', 'مادن', NULL),
(4, 'HONG_WEI', 'هونج وي', NULL),
(5, 'FARAG', 'فراج', NULL),
(6, 'EVERGREEN', 'إيفرجرين', NULL),
(7, 'FLOWER', 'فلاور', NULL),
(8, 'DL_DINGLI', 'دينجلي', NULL),
(9, 'MIDGO', 'ميدجو', NULL),
(10, 'PASCO', 'باسكو', NULL),
(11, 'ELUCKY_EVERLUCKY', 'إيفر لاكي', NULL),
(12, 'SOFI PLAST', 'سوفي بلاست', NULL),
(13, 'SEMA', 'سيما', NULL),
(14, 'BRAVO', 'برافو', NULL),
(15, 'SASCO', 'ساسكو', NULL),
(16, 'DOMS', 'دومز', NULL),
(17, 'ALWARRAK', 'الوراق', NULL),
(18, 'MICHAEL', 'مايكل', NULL),
(19, 'GAOERJIEFU', 'غاورجيفو', NULL),
(20, 'MICRO', 'مايكرو', NULL),
(21, 'QUEEN', 'كوين', NULL),
(22, 'PRIMA', 'بريما', NULL),
(23, 'ROTO', 'روتو', NULL),
(24, 'PENSAN', 'بنسان', NULL),
(25, 'MAPED', 'مابيد', NULL),
(26, 'DU HU', 'دو هو', NULL),
(27, 'GAZELLE', 'غزال', NULL),
(28, 'ELSAFA', 'الصفا', NULL),
(29, 'ALADIB', 'الأديب', NULL),
(30, 'HOMSON', 'هومسون', NULL),
(31, 'ETMAN GROUP', 'عتمان', NULL),
(32, 'KANEX', 'كانكس', NULL),
(33, 'GOLDEN_TAPE', 'جولدن تيب', NULL),
(34, 'KANGARO', 'كانجارو', NULL),
(35, 'SELECT', 'سيليكت', NULL),
(36, 'RAMSIS', 'رمسيس', NULL),
(37, 'AMIRA FACTORY ALEX', 'مصنع أميرة', NULL),
(38, 'ELNOUR', 'النور', NULL),
(39, 'KINGMAX', 'كينج ماكس', NULL),
(40, 'GHARIB', 'أولاد غريب', NULL),
(41, 'SENA', 'سنا', NULL),
(42, 'STD', 'إس تي دي', NULL),
(43, 'MAHGOUB', 'محجوب', NULL),
(44, 'O & A', 'أو أند إيه', NULL),
(45, 'DONG A', 'دونج إيه', NULL),
(46, 'ANDLOSYA GROUP', 'أندلسية', NULL),
(47, 'KARUIDA', 'كارويدا', NULL),
(48, 'CASINE', 'كاسين', NULL),
(49, 'PHILIPS', 'فيليبس', NULL),
(50, 'GELCY', 'جيلسي', NULL),
(51, 'AL_AZHARI', 'الأزهري', NULL),
(52, 'POWER', 'باور', NULL),
(53, 'DIGITAL', 'ديجيتال', NULL),
(54, 'CHANYI', 'تشان يي', NULL),
(55, 'ROTRING', 'روترينج', NULL)
ON CONFLICT (id) DO NOTHING;

-- 2. خطوة حاسمة: تعديل الـ Sequence لكي يبدأ من أخر ID أدخلناه (58 + 1 = 59)
SELECT setval(pg_get_serial_sequence('public.brands', 'id'), COALESCE(MAX(id), 1)) FROM public.brands;