-- ========================================================
-- Insert Products Seed Data (Starting from ID 1)
-- ========================================================
INSERT INTO public.products (id, category_id, name, name_ar) VALUES 
(1, 212, 'Glue stick', 'جلو ستيك'),
(2, 212, 'Sellotape', 'شريط لاصق سلوتيب'),
(3, 603, 'Colored Pencil', 'ألوان خشب'),
(4, 501, 'Calculator', 'ألة حاسبة'),
(5, 501, 'Dry Cell Battery', 'بطارية جافة'),
(6, 203, 'Correction Pen', 'قلم كوريكتور'),
(7, 203, 'Eraser', 'استيكة'),
(8, 401, 'Pocket Display Book', 'هولدر جيوب متعددة'),
(9, 401, 'U-Shape Sheet Protector', 'حافظة حرف يو'),
(10, 401, 'L-Shape Sheet Protector', 'حافظة حرف إل'),
(11, 401, 'Envelope', 'ظرف'),
(12, 401, 'Plastic Envelope with Button', 'حافظة كبسولة'),
(13, 401, 'Zipper Document Wallet', 'حافظة سوستة'),
(14, 401, 'Loose-Leaf Ring Binder', 'كلاسير حلقات'),
(15, 401, 'Slide Binder', 'دوسيه مسطرة'),
(16, 602, 'Stencil Ruler', 'مسطرة أشكال'),
(17, 802, 'Wrapping Ribbon', 'شريط لف الهدايا'),
(18, 306, 'Legal Contract', 'عقود'),
(19, 306, 'Receipt', 'إيصالات'),
(20, 306, 'registration folder', 'ملف تقديم'),
(21, 205, 'Whiteboard Marker', 'قلم سبورة'),
(22, 205, 'Permanent Marker', 'قلم ماركر دائم'),
(23, 205, 'Highlighter', 'قلم هاي لايتر'),
(24, 801, 'Modeling Clay', 'صلصال'),
(25, 101, 'Pocket Notebook', 'نوت بوك صغيرة'),
(26, 101, 'Exercise Book', 'كراسة'),
(27, 101, 'Notebook', 'كشكول'),
(28, 101, 'Ruled Paper', 'ورق مسطر'),
(29, 802, 'Balloon', 'بالون'),
(30, 701, 'Pencil Case', 'مقلمة'),
(31, 201, 'Pencil Sharpener', 'براية'),
(32, 201, 'Graphite Pencil', 'قلم رصاص'),
(33, 201, 'Mechanical Pencil', 'قلم رصاص سنون'),
(34, 206, 'Pen', 'قلم جاف'),
(35, 304, 'Invoice Book', 'دفتر فواتير'),
(36, 304, 'Price Labels', 'ملصقات الأسعار'),
(37, 304, 'Thermal Paper Roll', 'بكر حراري'),
(38, 401, 'Report Cover', 'دوسيه تقارير'),
(39, 305, 'Rubber Bands', 'أساتك'),
(40, 603, 'Sketchbook', 'كراس رسم'),
(41, 302, 'Stamp Pad Refill Ink', 'حبر ختامة'),
(42, 305, 'Bulldog Clip', 'مشبك ورق'),
(43, 305, 'Clipboard', 'بلانشيطة'),
(44, 305, 'Sticky Note', 'سيتكي نوت'),
(45, 501, 'USB Flash Drive', 'فلاش ميموري'),
(46, 212, 'Glue Gun Stick', 'غيار مسدس شمع'),
(47, 602, 'Protractor', 'منقلة'),
(48, 602, 'Ruler', 'مسطرة'),
(49, 602, 'Compass', 'برجل'),
(50, 306, 'Lease agreement', 'عقد إيجار'),
(51, 304, 'Custom Invoice Book', 'دفتر فواتير مخصص')
ON CONFLICT (id) DO NOTHING;

-- Synchronize sequence after manual ID inserts
SELECT setval(
    pg_get_serial_sequence('public.products', 'id'), 
    COALESCE(MAX(id), 1),
    (MAX(id) IS NOT NULL)
) FROM public.products;